build:
  env:
    - CGO_ENABLED=0
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}}

archives:
- format: binary
  name_template: "svcmgr_{{.Os}}_{{.Arch}}"

checksum:
  name_template: 'checksums.txt'
