name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go 1.21
      uses: actions/setup-go@v3
      with:
        go-version: 1.21

    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: go mod tidy

    - name: Build
      run: go build -v ./...

    - name: Run tests
      run: go test -v ./...
